---

- name : yum update
  yum :
    name: "*"
    state: latest

- name : install epel
  yum :
    name: "epel-release"
    state: present

- name: install wget
  yum:
    name: "{{ item }}"
    state: present
    with_items:
      - wget
      - net-tools
      - bind-utils

- name: install bash-completion
  yum:
    name: "bash-completion"
    state: present

- name: bash-completion
  command: wget https://github.com/terralinux/systemd/raw/master/src/systemctl-bash-completion.sh -O /etc/bash_completion.d/systemctl-bash-completion.sh

- name: make directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.vim"
    state: directory

- name: add vim rc
  copy:
    src: vimrc
    dest: "{{ lookup('env', 'HOME') }}/.vim"

- name: add molo
  copy:
    direcotry: yes
    src: color
    dest: "{{ lookup('env', 'HOME') }}/.vim/"

- name: Get SELinux Mode
  shell: getenforce
  register: selinux_status
  changed_when: False

- name: debug
  debug: var=selinux_status

- name: Install libselinux-python
  yum: name=libselinux-python state=present
  when: selinux_status.stdout == 'Enforcing'

- name: Disable SElinux
  selinux:
   state: disabled
  when: selinux_status.stdout == 'Enforcing'

- name: Reboot System
  shell: "sleep 2 && reboot"
  async: 1
  poll: 0
  when: selinux_status.stdout == 'Enforcing'

- name: System boot up wait...
  local_action: wait_for host={{ansible_ssh_host}} port={{ansible_ssh_port}} delay=30
  become: false
  when: selinux_status.stdout == 'Enforcing'
